# Generated by Django 2.2.2 on 2019-07-02 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tsiahpng.default


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Category name')),
                ('ordering', models.IntegerField(db_index=True, default=-1, verbose_name='Ordering')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['-ordering'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alias', models.CharField(blank=True, max_length=256, null=True, verbose_name='Order alias')),
                ('order_date', models.DateField(db_index=True, default=tsiahpng.default.default_order_date, verbose_name='Order date')),
                ('is_available', models.BooleanField(default=True, help_text='Unselect this to prevent users from ordering.', verbose_name='Available for ordering')),
                ('is_active', models.BooleanField(default=True, help_text='Unselect this instead of deleting order.', verbose_name='Active')),
                ('note', models.TextField(blank=True, help_text='You can warp text by *stars* to <em>emphasize</em> it, **double stars** to make it <strong>bolder</strong> and ~~tilde~~ to <strike>delete</strike> it.', null=True, verbose_name='Note')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-order_date', '-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='Product name')),
                ('is_active', models.BooleanField(default=True, help_text='Unselect this instead of deleting product.', verbose_name='Active')),
                ('changeable', models.BooleanField(default=True, help_text='Unchecked if users are not allowed to make changes.', verbose_name='Changeable')),
                ('mergable', models.BooleanField(default=True, help_text='Unchecked if its quantity should not be summarized.', verbose_name='Mergable')),
                ('ordering', models.IntegerField(db_index=True, default=-1, verbose_name='Ordering')),
                ('price', models.PositiveIntegerField(default=25, verbose_name='Price')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tsiahpng.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['category', '-ordering'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Shop name')),
                ('ordering', models.IntegerField(db_index=True, default=-1, verbose_name='Ordering')),
                ('is_active', models.BooleanField(default=True, help_text='Unselect this instead of deleting shop.', verbose_name='Active')),
                ('changeable', models.BooleanField(default=True, help_text='Uncheckeded if users are not allowed to change menu.', verbose_name='Changeable')),
                ('image', models.ImageField(blank=True, help_text='Menu or shop photo.', null=True, upload_to='', verbose_name='Image')),
                ('note', models.TextField(blank=True, help_text='You can warp text by *stars* to <em>emphasize</em> it, **double stars** to make it <strong>bolder</strong> and ~~tilde~~ to <strike>delete</strike> it.', null=True, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
                'ordering': ['-ordering'],
            },
        ),
        migrations.CreateModel(
            name='SummaryText',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alias', models.CharField(blank=True, max_length=256, null=True, verbose_name='Template name')),
                ('template', models.TextField(help_text='To write template, see the introduction below.', verbose_name='Template')),
                ('ordering', models.IntegerField(db_index=True, default=-1, verbose_name='Ordering')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Template of summary text',
                'verbose_name_plural': 'Templates of summary text',
                'ordering': ['-ordering'],
            },
        ),
        migrations.CreateModel(
            name='WelcomeText',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, max_length=256, null=True, verbose_name='Subtitle')),
                ('is_active', models.BooleanField(default=True, help_text='Unselect this to disable this text.', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Welcome Text',
                'verbose_name_plural': 'Welcome Texts',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('cost', models.IntegerField(default=0, verbose_name='Cost')),
                ('note', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Note')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tsiahpng.Product', verbose_name='Ordered Product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsiahpng.Order', verbose_name='Order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Ordered Item',
                'verbose_name_plural': 'Ordered Items',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsiahpng.Shop', verbose_name='Shop'),
        ),
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tsiahpng.Shop', verbose_name='Shop'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('shop', 'name')},
        ),
    ]
