# Generated by Django 2.2.3 on 2019-07-29 11:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsiahpng', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=30, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='changeable',
            field=models.BooleanField(default=True, help_text='Unchecked if users are not allowed to change menu.', verbose_name='Changeable'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cost',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity'),
        ),
    ]
